# Generated by Django 4.2.11 on 2024-04-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
